-- Schema snapshot: prints the whole `public` schema as one SQL script.
--
-- READ ONLY. It only reads the system catalogs; it creates, changes and
-- deletes nothing, and it reads no table data.
--
-- How to use: Supabase dashboard, SQL Editor, New query, paste this whole
-- file, Run. The result is one row with one cell, `schema_sql`. Copy that
-- cell (or export the result) and save it as `supabase/schema/public.sql`.
--
-- Why it exists: the core tables (clinics, demographics_raw, ...) were made
-- by clicking in the dashboard, so no migration file describes them, and
-- Supabase does not keep a history of SQL run in the editor. This captures
-- what the database actually is, including anything changed by hand.
--
-- What it covers, in this order: sequences, tables (columns, defaults,
-- identity, not null), constraints (primary, unique, check, then foreign
-- keys), indexes, functions, views, triggers, row level security and every
-- policy, and the table grants for anon / authenticated / service_role.
-- It does not cover Supabase's own schemas (auth, storage, realtime).
--
-- The weekly "Schema snapshot" GitHub Action produces the same record with
-- pg_dump, so after its first run this query is a fallback.

with
tbl as (
  select c.oid, c.relname, c.relkind
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind in ('r', 'p')
),
seqs as (
  select 1 as sec, c.relname as k, 0 as sub,
         format('create sequence if not exists public.%I;', c.relname) as ddl
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind = 'S'
    and not exists (                       -- identity sequences come with their column
      select 1 from pg_depend d
      where d.objid = c.oid and d.deptype = 'i')
),
cols as (
  select t.relname, a.attnum,
         format('  %I %s%s%s%s', a.attname,
           format_type(a.atttypid, a.atttypmod),
           case a.attidentity
             when 'a' then ' generated always as identity'
             when 'd' then ' generated by default as identity' else '' end,
           case when a.attgenerated = 's'
             then format(' generated always as (%s) stored', pg_get_expr(ad.adbin, ad.adrelid))
             when ad.adbin is not null
             then ' default ' || pg_get_expr(ad.adbin, ad.adrelid) else '' end,
           case when a.attnotnull then ' not null' else '' end) as line
  from tbl t
  join pg_attribute a on a.attrelid = t.oid and a.attnum > 0 and not a.attisdropped
  left join pg_attrdef ad on ad.adrelid = t.oid and ad.adnum = a.attnum
),
tables as (
  select 2 as sec, relname as k, 0 as sub,
         format(E'create table if not exists public.%I (\n%s\n);', relname,
                string_agg(line, E',\n' order by attnum)) as ddl
  from cols group by relname
),
cons as (
  select case when co.contype = 'f' then 4 else 3 end as sec,
         t.relname as k, 0 as sub,
         format('alter table public.%I add constraint %I %s;',
                t.relname, co.conname, pg_get_constraintdef(co.oid)) as ddl
  from pg_constraint co
  join tbl t on t.oid = co.conrelid
  where co.contype in ('p', 'u', 'c', 'f', 'x')
),
idx as (
  select 5 as sec, t.relname as k, 0 as sub,
         pg_get_indexdef(i.indexrelid) || ';' as ddl
  from pg_index i
  join tbl t on t.oid = i.indrelid
  where not exists (select 1 from pg_constraint co where co.conindid = i.indexrelid)
),
views as (
  select 7 as sec, c.relname as k, 0 as sub,
         format(E'create or replace view public.%I as\n%s', c.relname,
                pg_get_viewdef(c.oid, true)) as ddl
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind in ('v', 'm')
),
funcs as (
  select 6 as sec, p.proname as k, 0 as sub,
         pg_get_functiondef(p.oid) || ';' as ddl
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public' and p.prokind in ('f', 'p')
    and not exists (                       -- skip functions owned by extensions
      select 1 from pg_depend d
      where d.objid = p.oid and d.deptype = 'e')
),
trigs as (
  select 8 as sec, t.relname as k, 0 as sub,
         pg_get_triggerdef(tg.oid) || ';' as ddl
  from pg_trigger tg
  join tbl t on t.oid = tg.tgrelid
  where not tg.tgisinternal
),
rls as (
  select 9 as sec, c.relname as k, 0 as sub,
         format('alter table public.%I enable row level security;', c.relname)
         || case when c.relforcerowsecurity
              then format(E'\nalter table public.%I force row level security;', c.relname)
              else '' end as ddl
  from pg_class c join tbl t on t.oid = c.oid
  where c.relrowsecurity
),
pols as (
  select 10 as sec, p.tablename as k, 0 as sub,
         format('create policy %I on public.%I as %s for %s to %s%s%s;',
                p.policyname, p.tablename, lower(p.permissive), lower(p.cmd),
                array_to_string(p.roles, ', '),
                case when p.qual is not null then E'\n  using (' || p.qual || ')' else '' end,
                case when p.with_check is not null then E'\n  with check (' || p.with_check || ')' else '' end) as ddl
  from pg_policies p
  where p.schemaname = 'public'
),
grants as (
  select 11 as sec, g.table_name as k, 0 as sub,
         format('grant %s on public.%I to %s;',
                string_agg(lower(g.privilege_type), ', ' order by g.privilege_type),
                g.table_name, g.grantee) as ddl
  from information_schema.role_table_grants g
  where g.table_schema = 'public'
    and g.grantee in ('anon', 'authenticated', 'service_role')
  group by g.table_name, g.grantee
),
everything as (
  select * from seqs union all select * from tables union all select * from cons
  union all select * from idx union all select * from views union all select * from funcs
  union all select * from trigs union all select * from rls union all select * from pols
  union all select * from grants
)
select
  '-- public schema snapshot, taken ' || to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI') || E' UTC\n'
  || '-- ' || version() || E'\n\n'
  || string_agg(ddl, E'\n\n' order by sec, k, ddl)
  || E'\n' as schema_sql
from everything;
